### ISSUE TITLE
RaspBee II Configuration-Tool is shown as light

### ISSUE THREAD

**Issue by wernerlinsler** [xibriz/deconz-mqtt#2]
RaspBee deconz api shows its Configuration tool as light but lights[key]['state']['on'] does not exist.
I solved the issue and  filter out states without 'on' by an additional if in the function get_lights (file: lights.py):
....
line 55-> for key in self.lights:
                   if 'on' in self.lights[key]['state']:
                       state = 0 
...

**Comment by xibriz** [comment]
Fixed in PR #5
