### ISSUE TITLE
UTF Error with importin Names from Deconz

### ISSUE THREAD

**Issue by Kilowatt-W** [xibriz/deconz-mqtt#3]
Traceback (most recent call last):
  File "client.py", line 39, in <module>
    light.get_lights()
  File "/home/pi/deconz-mqtt/src/lights.py", line 61, in get_lights
    publish.single(self.topic_pub.format(group_name=group_name, light_name=light_name), state, hostname=self.mqtt_ip, port=self.mqtt_port)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)

can be fixed by adding to client.py : 👍 

_**import sys
reload(sys)
sys.setdefaultencoding('utf-8')**_

**Comment by xibriz** [comment]
Fixed in PR #4
